[package]
name = "replaceball_server"
version = "0.1.0"
edition = "2021"
publish.workspace = true

[dependencies]

[dependencies.replaceball_sim]
registry = "local-registry"
version = "0.5.0"
path = "../replaceball_sim/"
features = ["serde"]
