use replaceball_sim::prelude::*;

pub fn away_team() -> Team {
    Team {
        fielders: [
            Player {
                name: Some("Carl Atcher".to_string()),
                jersey_number: "12".to_string(),
                pitch_height_bias: 0,
                pitch_width_bias: 0,
                pitch_strike_bias: 0,
                pitcher_swing_on_ball_bias: 0,
                pitcher_contact_on_ball_bias: 0,
                pitcher_foul_on_ball_contact_bias: 0,
                pitcher_swing_on_strike_bias: 0,
                pitcher_contact_on_strike_bias: 0,
                pitcher_foul_on_strike_contact_bias: 0,
                pitcher_hit_direction_bias: 0,
                pitcher_launch_angle_bias: 0,
                pitcher_hit_speed_bias: 0,
                hitter_swing_on_ball_bias: 13,
                hitter_contact_on_ball_bias: -13,
                hitter_foul_on_ball_contact_bias: 20,
                hitter_swing_on_strike_bias: 15,
                hitter_contact_on_strike_bias: 11,
                hitter_foul_on_strike_contact_bias: -15,
                hitter_hit_direction_bias: 0,
                hitter_launch_angle_bias: 0,
                hitter_hit_speed_bias: 14,
                fielder_run_speed_bias: -14,
                fielder_reaction_time_bias: 15,
                fielder_throw_speed_bias: 18,
                fielder_transfer_time_bias: 20,
                baserunner_run_speed_bias: -18,
                baserunner_rounding_time_bias: -12,
                baserunner_box_exit_time_bias: -14,
                baserunner_takeoff_delay_bias: -20,
            },
            Player {
                name: Some("Pete Itcher".to_string()),
                jersey_number: "1".to_string(),
                pitch_height_bias: -15,
                pitch_width_bias: 0,
                pitch_strike_bias: 20,
                pitcher_swing_on_ball_bias: 15,
                pitcher_contact_on_ball_bias: -12,
                pitcher_foul_on_ball_contact_bias: 15,
                pitcher_swing_on_strike_bias: 16,
                pitcher_contact_on_strike_bias: 11,
                pitcher_foul_on_strike_contact_bias: 11,
                pitcher_hit_direction_bias: 0,
                pitcher_launch_angle_bias: -15,
                pitcher_hit_speed_bias: 16,
                hitter_swing_on_ball_bias: 20,
                hitter_contact_on_ball_bias: -20,
                hitter_foul_on_ball_contact_bias: -20,
                hitter_swing_on_strike_bias: -15,
                hitter_contact_on_strike_bias: -20,
                hitter_foul_on_strike_contact_bias: 0,
                hitter_hit_direction_bias: 0,
                hitter_launch_angle_bias: 0,
                hitter_hit_speed_bias: -20,
                fielder_run_speed_bias: -5,
                fielder_reaction_time_bias: -40,
                fielder_throw_speed_bias: 25,
                fielder_transfer_time_bias: 0,
                baserunner_run_speed_bias: -5,
                baserunner_rounding_time_bias: -10,
                baserunner_box_exit_time_bias: -20,
                baserunner_takeoff_delay_bias: -30,
            },
            Player {
                name: Some("Frank Batcher".to_string()),
                jersey_number: "77".to_string(),
                pitch_height_bias: 0,
                pitch_width_bias: 0,
                pitch_strike_bias: 0,
                pitcher_swing_on_ball_bias: 0,
                pitcher_contact_on_ball_bias: 0,
                pitcher_foul_on_ball_contact_bias: 0,
                pitcher_swing_on_strike_bias: 0,
                pitcher_contact_on_strike_bias: 0,
                pitcher_foul_on_strike_contact_bias: 0,
                pitcher_hit_direction_bias: 0,
                pitcher_launch_angle_bias: 0,
                pitcher_hit_speed_bias: 0,
                hitter_swing_on_ball_bias: 40,
                hitter_contact_on_ball_bias: -20,
                hitter_foul_on_ball_contact_bias: 0,
                hitter_swing_on_strike_bias: 40,
                hitter_contact_on_strike_bias: -10,
                hitter_foul_on_strike_contact_bias: -20,
                hitter_hit_direction_bias: 40,
                hitter_launch_angle_bias: 40,
                hitter_hit_speed_bias: 40,
                fielder_run_speed_bias: -50,
                fielder_reaction_time_bias: -20,
                fielder_throw_speed_bias: -20,
                fielder_transfer_time_bias: -50,
                baserunner_run_speed_bias: -50,
                baserunner_rounding_time_bias: -50,
                baserunner_box_exit_time_bias: -50,
                baserunner_takeoff_delay_bias: -50,
            },
            Player {
                name: Some("Sam Brown".to_string()),
                jersey_number: "12".to_string(),
                pitch_height_bias: 0,
                pitch_width_bias: 0,
                pitch_strike_bias: 0,
                pitcher_swing_on_ball_bias: 0,
                pitcher_contact_on_ball_bias: 0,
                pitcher_foul_on_ball_contact_bias: 0,
                pitcher_swing_on_strike_bias: 0,
                pitcher_contact_on_strike_bias: 0,
                pitcher_foul_on_strike_contact_bias: 0,
                pitcher_hit_direction_bias: 0,
                pitcher_launch_angle_bias: 0,
                pitcher_hit_speed_bias: 0,
                hitter_swing_on_ball_bias: -30,
                hitter_contact_on_ball_bias: 40,
                hitter_foul_on_ball_contact_bias: 60,
                hitter_swing_on_strike_bias: 50,
                hitter_contact_on_strike_bias: 60,
                hitter_foul_on_strike_contact_bias: -20,
                hitter_hit_direction_bias: 0,
                hitter_launch_angle_bias: -25,
                hitter_hit_speed_bias: -25,
                fielder_run_speed_bias: 10,
                fielder_reaction_time_bias: 30,
                fielder_throw_speed_bias: 10,
                fielder_transfer_time_bias: 10,
                baserunner_run_speed_bias: 40,
                baserunner_rounding_time_bias: 10,
                baserunner_box_exit_time_bias: 10,
                baserunner_takeoff_delay_bias: 10,
            },
            Player {
                name: Some("Tim Bennett".to_string()),
                jersey_number: "32".to_string(),
                pitch_height_bias: 0,
                pitch_width_bias: 0,
                pitch_strike_bias: 0,
                pitcher_swing_on_ball_bias: 0,
                pitcher_contact_on_ball_bias: 0,
                pitcher_foul_on_ball_contact_bias: 0,
                pitcher_swing_on_strike_bias: 0,
                pitcher_contact_on_strike_bias: 0,
                pitcher_foul_on_strike_contact_bias: 0,
                pitcher_hit_direction_bias: 0,
                pitcher_launch_angle_bias: 0,
                pitcher_hit_speed_bias: 0,
                hitter_swing_on_ball_bias: 0,
                hitter_contact_on_ball_bias: 0,
                hitter_foul_on_ball_contact_bias: 0,
                hitter_swing_on_strike_bias: 0,
                hitter_contact_on_strike_bias: 0,
                hitter_foul_on_strike_contact_bias: 0,
                hitter_hit_direction_bias: 0,
                hitter_launch_angle_bias: 0,
                hitter_hit_speed_bias: 0,
                fielder_run_speed_bias: 0,
                fielder_reaction_time_bias: 0,
                fielder_throw_speed_bias: 0,
                fielder_transfer_time_bias: 0,
                baserunner_run_speed_bias: 0,
                baserunner_rounding_time_bias: 0,
                baserunner_box_exit_time_bias: 0,
                baserunner_takeoff_delay_bias: 0,
            },
            Player {
                name: Some("Sophia Sanchez".to_string()),
                jersey_number: "41".to_string(),
                pitch_height_bias: 0,
                pitch_width_bias: 0,
                pitch_strike_bias: 0,
                pitcher_swing_on_ball_bias: 0,
                pitcher_contact_on_ball_bias: 0,
                pitcher_foul_on_ball_contact_bias: 0,
                pitcher_swing_on_strike_bias: 0,
                pitcher_contact_on_strike_bias: 0,
                pitcher_foul_on_strike_contact_bias: 0,
                pitcher_hit_direction_bias: 0,
                pitcher_launch_angle_bias: 0,
                pitcher_hit_speed_bias: 0,
                hitter_swing_on_ball_bias: 50,
                hitter_contact_on_ball_bias: 0,
                hitter_foul_on_ball_contact_bias: 0,
                hitter_swing_on_strike_bias: 70,
                hitter_contact_on_strike_bias: 30,
                hitter_foul_on_strike_contact_bias: -20,
                hitter_hit_direction_bias: -40,
                hitter_launch_angle_bias: 10,
                hitter_hit_speed_bias: 10,
                fielder_run_speed_bias: 60,
                fielder_reaction_time_bias: 50,
                fielder_throw_speed_bias: 40,
                fielder_transfer_time_bias: 30,
                baserunner_run_speed_bias: 60,
                baserunner_rounding_time_bias: 50,
                baserunner_box_exit_time_bias: 40,
                baserunner_takeoff_delay_bias: 30,
            },
            Player {
                name: Some("Larry Foster".to_string()),
                jersey_number: "12".to_string(),
                pitch_height_bias: 0,
                pitch_width_bias: 0,
                pitch_strike_bias: 0,
                pitcher_swing_on_ball_bias: 0,
                pitcher_contact_on_ball_bias: 0,
                pitcher_foul_on_ball_contact_bias: 0,
                pitcher_swing_on_strike_bias: 0,
                pitcher_contact_on_strike_bias: 0,
                pitcher_foul_on_strike_contact_bias: 0,
                pitcher_hit_direction_bias: 0,
                pitcher_launch_angle_bias: 0,
                pitcher_hit_speed_bias: 0,
                hitter_swing_on_ball_bias: -50,
                hitter_contact_on_ball_bias: -60,
                hitter_foul_on_ball_contact_bias: -70,
                hitter_swing_on_strike_bias: 0,
                hitter_contact_on_strike_bias: 30,
                hitter_foul_on_strike_contact_bias: -40,
                hitter_hit_direction_bias: 100,
                hitter_launch_angle_bias: 60,
                hitter_hit_speed_bias: 60,
                fielder_run_speed_bias: 0,
                fielder_reaction_time_bias: 30,
                fielder_throw_speed_bias: 50,
                fielder_transfer_time_bias: 0,
                baserunner_run_speed_bias: 0,
                baserunner_rounding_time_bias: 0,
                baserunner_box_exit_time_bias: 0,
                baserunner_takeoff_delay_bias: 0,
            },
            Player {
                name: Some("Chris Fisher".to_string()),
                jersey_number: "12".to_string(),
                pitch_height_bias: 0,
                pitch_width_bias: 0,
                pitch_strike_bias: 0,
                pitcher_swing_on_ball_bias: 0,
                pitcher_contact_on_ball_bias: 0,
                pitcher_foul_on_ball_contact_bias: 0,
                pitcher_swing_on_strike_bias: 0,
                pitcher_contact_on_strike_bias: 0,
                pitcher_foul_on_strike_contact_bias: 0,
                pitcher_hit_direction_bias: 0,
                pitcher_launch_angle_bias: 0,
                pitcher_hit_speed_bias: 0,
                hitter_swing_on_ball_bias: 0,
                hitter_contact_on_ball_bias: 10,
                hitter_foul_on_ball_contact_bias: 10,
                hitter_swing_on_strike_bias: 10,
                hitter_contact_on_strike_bias: 10,
                hitter_foul_on_strike_contact_bias: 10,
                hitter_hit_direction_bias: 0,
                hitter_launch_angle_bias: -30,
                hitter_hit_speed_bias: -75,
                fielder_run_speed_bias: 100,
                fielder_reaction_time_bias: 20,
                fielder_throw_speed_bias: 30,
                fielder_transfer_time_bias: 10,
                baserunner_run_speed_bias: 100,
                baserunner_rounding_time_bias: 20,
                baserunner_box_exit_time_bias: 30,
                baserunner_takeoff_delay_bias: 10,
            },
            Player {
                name: Some("Rachel Fields".to_string()),
                jersey_number: "12".to_string(),
                pitch_height_bias: 0,
                pitch_width_bias: 0,
                pitch_strike_bias: 0,
                pitcher_swing_on_ball_bias: 0,
                pitcher_contact_on_ball_bias: 0,
                pitcher_foul_on_ball_contact_bias: 0,
                pitcher_swing_on_strike_bias: 0,
                pitcher_contact_on_strike_bias: 0,
                pitcher_foul_on_strike_contact_bias: 0,
                pitcher_hit_direction_bias: 0,
                pitcher_launch_angle_bias: 0,
                pitcher_hit_speed_bias: 0,
                hitter_swing_on_ball_bias: 10,
                hitter_contact_on_ball_bias: 10,
                hitter_foul_on_ball_contact_bias: 10,
                hitter_swing_on_strike_bias: 10,
                hitter_contact_on_strike_bias: 10,
                hitter_foul_on_strike_contact_bias: 10,
                hitter_hit_direction_bias: 10,
                hitter_launch_angle_bias: 10,
                hitter_hit_speed_bias: 10,
                fielder_run_speed_bias: 10,
                fielder_reaction_time_bias: 10,
                fielder_throw_speed_bias: 10,
                fielder_transfer_time_bias: 10,
                baserunner_run_speed_bias: 10,
                baserunner_rounding_time_bias: 10,
                baserunner_box_exit_time_bias: 10,
                baserunner_takeoff_delay_bias: 10,
            },
        ],
        batting_order: [
            Fielder::SecondBase,
            Fielder::CenterFielder,
            Fielder::Shortstop,
            Fielder::LeftFielder,
            Fielder::FirstBase,
            Fielder::RightFielder,
            Fielder::Catcher,
            Fielder::Pitcher,
            Fielder::ThirdBase,
        ]
    }
}

pub fn home_team() -> Team {
    let base_stat = 12;

    Team {
        fielders: [
            Player {
                name: Some("Lefty McGillicuddy".to_string()),
                jersey_number: "27".to_string(),
                pitch_height_bias: 0,
                pitch_width_bias: 0,
                pitch_strike_bias: 0,
                pitcher_swing_on_ball_bias: 0,
                pitcher_contact_on_ball_bias: 0,
                pitcher_foul_on_ball_contact_bias: 0,
                pitcher_swing_on_strike_bias: 0,
                pitcher_contact_on_strike_bias: 0,
                pitcher_foul_on_strike_contact_bias: 0,
                pitcher_hit_direction_bias: 0,
                pitcher_launch_angle_bias: 0,
                pitcher_hit_speed_bias: 0,
                hitter_swing_on_ball_bias: base_stat,
                hitter_contact_on_ball_bias: base_stat,
                hitter_foul_on_ball_contact_bias: base_stat,
                hitter_swing_on_strike_bias: base_stat,
                hitter_contact_on_strike_bias: base_stat,
                hitter_foul_on_strike_contact_bias: base_stat,
                hitter_hit_direction_bias: 0,
                hitter_launch_angle_bias: 0,
                hitter_hit_speed_bias: base_stat,
                fielder_run_speed_bias: base_stat,
                fielder_reaction_time_bias: base_stat,
                fielder_throw_speed_bias: base_stat,
                fielder_transfer_time_bias: base_stat,
                baserunner_run_speed_bias: base_stat,
                baserunner_rounding_time_bias: base_stat,
                baserunner_box_exit_time_bias: base_stat,
                baserunner_takeoff_delay_bias: 20,
            },
            Player {
                name: Some("Slick Thompson".to_string()),
                jersey_number: "19".to_string(),
                pitch_height_bias: base_stat,
                pitch_width_bias: base_stat,
                pitch_strike_bias: base_stat,
                pitcher_swing_on_ball_bias: base_stat,
                pitcher_contact_on_ball_bias: base_stat,
                pitcher_foul_on_ball_contact_bias: base_stat,
                pitcher_swing_on_strike_bias: base_stat,
                pitcher_contact_on_strike_bias: base_stat,
                pitcher_foul_on_strike_contact_bias: base_stat,
                pitcher_hit_direction_bias: base_stat,
                pitcher_launch_angle_bias: base_stat,
                pitcher_hit_speed_bias: base_stat,
                hitter_swing_on_ball_bias: base_stat,
                hitter_contact_on_ball_bias: base_stat,
                hitter_foul_on_ball_contact_bias: base_stat,
                hitter_swing_on_strike_bias: base_stat,
                hitter_contact_on_strike_bias: base_stat,
                hitter_foul_on_strike_contact_bias: base_stat,
                hitter_hit_direction_bias: 0,
                hitter_launch_angle_bias: 0,
                hitter_hit_speed_bias: base_stat,
                fielder_run_speed_bias: base_stat,
                fielder_reaction_time_bias: base_stat,
                fielder_throw_speed_bias: base_stat,
                fielder_transfer_time_bias: base_stat,
                baserunner_run_speed_bias: base_stat,
                baserunner_rounding_time_bias: base_stat,
                baserunner_box_exit_time_bias: base_stat,
                baserunner_takeoff_delay_bias: 20,
            },
            Player {
                name: Some("Stumpy O'Malley".to_string()),
                jersey_number: "33".to_string(),
                pitch_height_bias: 0,
                pitch_width_bias: 0,
                pitch_strike_bias: 0,
                pitcher_swing_on_ball_bias: 0,
                pitcher_contact_on_ball_bias: 0,
                pitcher_foul_on_ball_contact_bias: 0,
                pitcher_swing_on_strike_bias: 0,
                pitcher_contact_on_strike_bias: 0,
                pitcher_foul_on_strike_contact_bias: 0,
                pitcher_hit_direction_bias: 0,
                pitcher_launch_angle_bias: 0,
                pitcher_hit_speed_bias: 0,
                hitter_swing_on_ball_bias: base_stat,
                hitter_contact_on_ball_bias: base_stat,
                hitter_foul_on_ball_contact_bias: base_stat,
                hitter_swing_on_strike_bias: base_stat,
                hitter_contact_on_strike_bias: base_stat,
                hitter_foul_on_strike_contact_bias: base_stat,
                hitter_hit_direction_bias: 0,
                hitter_launch_angle_bias: 0,
                hitter_hit_speed_bias: base_stat,
                fielder_run_speed_bias: base_stat,
                fielder_reaction_time_bias: base_stat,
                fielder_throw_speed_bias: base_stat,
                fielder_transfer_time_bias: base_stat,
                baserunner_run_speed_bias: base_stat,
                baserunner_rounding_time_bias: base_stat,
                baserunner_box_exit_time_bias: base_stat,
                baserunner_takeoff_delay_bias: 20,
            },
            Player {
                name: Some("\"Biscuit\" Fitzgerald".to_string()),
                jersey_number: "14".to_string(),
                pitch_height_bias: 0,
                pitch_width_bias: 0,
                pitch_strike_bias: 0,
                pitcher_swing_on_ball_bias: 0,
                pitcher_contact_on_ball_bias: 0,
                pitcher_foul_on_ball_contact_bias: 0,
                pitcher_swing_on_strike_bias: 0,
                pitcher_contact_on_strike_bias: 0,
                pitcher_foul_on_strike_contact_bias: 0,
                pitcher_hit_direction_bias: 0,
                pitcher_launch_angle_bias: 0,
                pitcher_hit_speed_bias: 0,
                hitter_swing_on_ball_bias: base_stat,
                hitter_contact_on_ball_bias: base_stat,
                hitter_foul_on_ball_contact_bias: base_stat,
                hitter_swing_on_strike_bias: base_stat,
                hitter_contact_on_strike_bias: base_stat,
                hitter_foul_on_strike_contact_bias: base_stat,
                hitter_hit_direction_bias: 0,
                hitter_launch_angle_bias: 0,
                hitter_hit_speed_bias: base_stat,
                fielder_run_speed_bias: base_stat,
                fielder_reaction_time_bias: base_stat,
                fielder_throw_speed_bias: base_stat,
                fielder_transfer_time_bias: base_stat,
                baserunner_run_speed_bias: base_stat,
                baserunner_rounding_time_bias: base_stat,
                baserunner_box_exit_time_bias: base_stat,
                baserunner_takeoff_delay_bias: 20,
            },
            Player {
                name: Some("Rube Sullivan".to_string()),
                jersey_number: "22".to_string(),
                pitch_height_bias: 0,
                pitch_width_bias: 0,
                pitch_strike_bias: 0,
                pitcher_swing_on_ball_bias: 0,
                pitcher_contact_on_ball_bias: 0,
                pitcher_foul_on_ball_contact_bias: 0,
                pitcher_swing_on_strike_bias: 0,
                pitcher_contact_on_strike_bias: 0,
                pitcher_foul_on_strike_contact_bias: 0,
                pitcher_hit_direction_bias: 0,
                pitcher_launch_angle_bias: 0,
                pitcher_hit_speed_bias: 0,
                hitter_swing_on_ball_bias: base_stat,
                hitter_contact_on_ball_bias: base_stat,
                hitter_foul_on_ball_contact_bias: base_stat,
                hitter_swing_on_strike_bias: base_stat,
                hitter_contact_on_strike_bias: base_stat,
                hitter_foul_on_strike_contact_bias: base_stat,
                hitter_hit_direction_bias: 0,
                hitter_launch_angle_bias: 0,
                hitter_hit_speed_bias: base_stat,
                fielder_run_speed_bias: base_stat,
                fielder_reaction_time_bias: base_stat,
                fielder_throw_speed_bias: base_stat,
                fielder_transfer_time_bias: base_stat,
                baserunner_run_speed_bias: base_stat,
                baserunner_rounding_time_bias: base_stat,
                baserunner_box_exit_time_bias: base_stat,
                baserunner_takeoff_delay_bias: 20,
            },
            Player {
                name: Some("Dusty Malone".to_string()),
                jersey_number: "88".to_string(),
                pitch_height_bias: 0,
                pitch_width_bias: 0,
                pitch_strike_bias: 0,
                pitcher_swing_on_ball_bias: 0,
                pitcher_contact_on_ball_bias: 0,
                pitcher_foul_on_ball_contact_bias: 0,
                pitcher_swing_on_strike_bias: 0,
                pitcher_contact_on_strike_bias: 0,
                pitcher_foul_on_strike_contact_bias: 0,
                pitcher_hit_direction_bias: 0,
                pitcher_launch_angle_bias: 0,
                pitcher_hit_speed_bias: 0,
                hitter_swing_on_ball_bias: base_stat,
                hitter_contact_on_ball_bias: base_stat,
                hitter_foul_on_ball_contact_bias: base_stat,
                hitter_swing_on_strike_bias: base_stat,
                hitter_contact_on_strike_bias: base_stat,
                hitter_foul_on_strike_contact_bias: base_stat,
                hitter_hit_direction_bias: 0,
                hitter_launch_angle_bias: 0,
                hitter_hit_speed_bias: base_stat,
                fielder_run_speed_bias: base_stat,
                fielder_reaction_time_bias: base_stat,
                fielder_throw_speed_bias: base_stat,
                fielder_transfer_time_bias: base_stat,
                baserunner_run_speed_bias: base_stat,
                baserunner_rounding_time_bias: base_stat,
                baserunner_box_exit_time_bias: base_stat,
                baserunner_takeoff_delay_bias: 20,
            },
            Player {
                name: Some("Butch Callahan".to_string()),
                jersey_number: "base_stat".to_string(),
                pitch_height_bias: 0,
                pitch_width_bias: 0,
                pitch_strike_bias: 0,
                pitcher_swing_on_ball_bias: 0,
                pitcher_contact_on_ball_bias: 0,
                pitcher_foul_on_ball_contact_bias: 0,
                pitcher_swing_on_strike_bias: 0,
                pitcher_contact_on_strike_bias: 0,
                pitcher_foul_on_strike_contact_bias: 0,
                pitcher_hit_direction_bias: 0,
                pitcher_launch_angle_bias: 0,
                pitcher_hit_speed_bias: 0,
                hitter_swing_on_ball_bias: base_stat,
                hitter_contact_on_ball_bias: base_stat,
                hitter_foul_on_ball_contact_bias: base_stat,
                hitter_swing_on_strike_bias: base_stat,
                hitter_contact_on_strike_bias: base_stat,
                hitter_foul_on_strike_contact_bias: base_stat,
                hitter_hit_direction_bias: 0,
                hitter_launch_angle_bias: 0,
                hitter_hit_speed_bias: base_stat,
                fielder_run_speed_bias: base_stat,
                fielder_reaction_time_bias: base_stat,
                fielder_throw_speed_bias: base_stat,
                fielder_transfer_time_bias: base_stat,
                baserunner_run_speed_bias: base_stat,
                baserunner_rounding_time_bias: base_stat,
                baserunner_box_exit_time_bias: base_stat,
                baserunner_takeoff_delay_bias: 20,
            },
            Player {
                name: Some("Buck McPherson".to_string()),
                jersey_number: "7".to_string(),
                pitch_height_bias: 0,
                pitch_width_bias: 0,
                pitch_strike_bias: 0,
                pitcher_swing_on_ball_bias: 0,
                pitcher_contact_on_ball_bias: 0,
                pitcher_foul_on_ball_contact_bias: 0,
                pitcher_swing_on_strike_bias: 0,
                pitcher_contact_on_strike_bias: 0,
                pitcher_foul_on_strike_contact_bias: 0,
                pitcher_hit_direction_bias: 0,
                pitcher_launch_angle_bias: 0,
                pitcher_hit_speed_bias: 0,
                hitter_swing_on_ball_bias: base_stat,
                hitter_contact_on_ball_bias: base_stat,
                hitter_foul_on_ball_contact_bias: base_stat,
                hitter_swing_on_strike_bias: base_stat,
                hitter_contact_on_strike_bias: base_stat,
                hitter_foul_on_strike_contact_bias: base_stat,
                hitter_hit_direction_bias: 0,
                hitter_launch_angle_bias: 0,
                hitter_hit_speed_bias: base_stat,
                fielder_run_speed_bias: base_stat,
                fielder_reaction_time_bias: base_stat,
                fielder_throw_speed_bias: base_stat,
                fielder_transfer_time_bias: base_stat,
                baserunner_run_speed_bias: base_stat,
                baserunner_rounding_time_bias: base_stat,
                baserunner_box_exit_time_bias: base_stat,
                baserunner_takeoff_delay_bias: 20,
            },
            Player {
                name: Some("Gabby Johnson".to_string()),
                jersey_number: "27".to_string(),
                pitch_height_bias: 0,
                pitch_width_bias: 0,
                pitch_strike_bias: 0,
                pitcher_swing_on_ball_bias: 0,
                pitcher_contact_on_ball_bias: 0,
                pitcher_foul_on_ball_contact_bias: 0,
                pitcher_swing_on_strike_bias: 0,
                pitcher_contact_on_strike_bias: 0,
                pitcher_foul_on_strike_contact_bias: 0,
                pitcher_hit_direction_bias: 0,
                pitcher_launch_angle_bias: 0,
                pitcher_hit_speed_bias: 0,
                hitter_swing_on_ball_bias: base_stat,
                hitter_contact_on_ball_bias: base_stat,
                hitter_foul_on_ball_contact_bias: base_stat,
                hitter_swing_on_strike_bias: base_stat,
                hitter_contact_on_strike_bias: base_stat,
                hitter_foul_on_strike_contact_bias: base_stat,
                hitter_hit_direction_bias: 0,
                hitter_launch_angle_bias: 0,
                hitter_hit_speed_bias: base_stat,
                fielder_run_speed_bias: base_stat,
                fielder_reaction_time_bias: base_stat,
                fielder_throw_speed_bias: base_stat,
                fielder_transfer_time_bias: base_stat,
                baserunner_run_speed_bias: base_stat,
                baserunner_rounding_time_bias: base_stat,
                baserunner_box_exit_time_bias: base_stat,
                baserunner_takeoff_delay_bias: 20,
            },
        ],
        batting_order: [
            Fielder::LeftFielder,
            Fielder::Shortstop,
            Fielder::RightFielder,
            Fielder::FirstBase,
            Fielder::CenterFielder,
            Fielder::Catcher,
            Fielder::SecondBase,
            Fielder::ThirdBase,
            Fielder::Pitcher,
        ]
    }
}
